from mcp.server.fastmcp import FastMCP
import uuid, random, datetime, ipaddress

ids_mcp = FastMCP("IDSServer")

@ids_mcp.tool()
def register_sensor(sensor_name: str, ip: str) -> dict:
    """
    Register a network sensor with the IDS backend.

    Parameters
    ----------
    sensor_name : str
        Friendly name of the sensor.
    ip : str
        IPv4 / IPv6 address where the sensor is deployed.

    Returns
    -------
    dict
        {
            "sensor_id": <str>,
            "registered_at": <str>
        }
    """
    return {"sensor_id": uuid.uuid4().hex, "registered_at": datetime.datetime.now(datetime.UTC).isoformat() + "Z"}


@ids_mcp.tool()
def poll_alerts(sensor_id: str, limit: int = 20) -> dict:
    """
    Retrieve recent IDS alerts generated by a sensor.

    Parameters
    ----------
    sensor_id : str
        Identifier returned by `register_sensor`.
    limit : int, optional
        Maximum number of alerts (default 20).

    Returns
    -------
    dict
        {
            "sensor_id": <str>,
            "alerts": [ { "alert_id": <str>, "severity": <str>, "src": <str>, "dst": <str> }, … ]
        }
    """
    severities = ["low", "medium", "high", "critical"]
    alerts = [
        {
            "alert_id": uuid.uuid4().hex[:12],
            "severity": random.choices(severities, weights=[50, 30, 15, 5])[0],
            "src": str(ipaddress.IPv4Address(random.randint(0x0B000000, 0xDF000000))),
            "dst": str(ipaddress.IPv4Address(random.randint(0x0B000000, 0xDF000000))),
        }
        for _ in range(limit)
    ]
    return {"sensor_id": sensor_id, "alerts": alerts}


if __name__ == "__main__":
    ids_mcp.run(transport="stdio")
